language: ruby
sudo: false
cache: bundler
rvm:
  - ruby-head
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
  - jruby
  - jruby-head
  - rbx-2
env:
  global:
    - CODECLIMATE_REPO_TOKEN=a682282424953217391072dbe4c6b0f793a6c40312a182bc1eb3e26337dbf0f1
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ed57a44a47758f95c362
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
