#!/bin/sh

if [ "$WORKSPACE" = "" -o "$JOB_NAME" = "" ]; then
  echo "\$WORKSPACE or \$JOB_NAME missing"
  exit 1
fi

CI_DIR="$WORKSPACE/ci"
ROOT_DIR="$CI_DIR/.."

export CI=1
export PROJECT="$JOB_NAME"
export COVERAGE=1

# RVM
source "$HOME/.rvm/scripts/rvm"
. $ROOT_DIR/.rvmrc

# database config
cp $CI_DIR/database.yml $ROOT_DIR/config

# run
bundle --without development install && bundle exec rake test
